version: '3'
services:
  db:
    image: mysql:8.4
    ports:
      - 3306:3306
    environment:
       MYSQL_ROOT_PASSWORD: ${DB_PWD}
       MYSQL_DATABASE: ${DB_NAME}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pmysql"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./mysql:/var/lib/mysql

  
  phpmyadmin:
    image: phpmyadmin:5.2
    ports: 
      - 8082:80
    environment:
       PMA_HOST: db
       PMA_USER: ${DB_USER}
       PMA_PASSWORD: ${DB_PWD}
    restart: unless-stopped

  app:
    build: ./docker-exercises
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      DB_USER: ${DB_USER}
      DB_PWD: ${DB_PWD}
      DB_SERVER: db
      DB_NAME: ${DB_NAME}
